apiVersion: v1
kind: Service
metadata:
 name: abacate
spec:
  ports:
  - name: abacate
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31852
  selector:
    tier: backend
    app: abacate
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: abacate
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: abacate 
        tier: backend
        track: stable
    spec:
      containers:
      - name: abacate
        image: haha:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            httpHeaders:
            - name: X-Custom-Header
              value: Awesome
          initialDelaySeconds: 3
          periodSeconds: 3





